export const DASHBOARD_DATA_REQUEST='DASHBOARD_DATA_REQUEST'
export const DASHBOARD_DATA_SUCCESS='DASHBOARD_DATA_SUCCESS'
export const DASHBOARD_DATA_FAIL='DASHBOARD_DATA_FAIL'



export const   CHANGE_PIN_REQUEST='CHANGE_PIN_REQUEST'
export const   CHANGE_PIN_SUCCESS='CHANGE_PIN_SUCCESS'
export const   CHANGE_PIN_FAIL='CHANGE_PIN_FAIL'

