export const COUNTRY_LIST_REQUEST='COUNTRY_LIST_REQUEST'
export const COUNTRY_LIST_SUCCESS='COUNTRY_LIST_SUCCESS'
export const COUNTRY_LIST_FAIL='COUNTRY_LIST_FAIL'


export const DISTRICT_LIST_REQUEST='DISTRICT_LIST_REQUEST'
export const DISTRICT_LIST_SUCCESS='DISTRICT_LIST_SUCCESS'
export const DISTRICT_LIST_FAIL='DISTRICT_LIST_FAIL'


export const PROVINCE_LIST_REQUEST='PROVINCE_LIST_REQUEST'
export const PROVINCE_LIST_SUCCESS='PROVINCE_LIST_SUCCESS'
export const PROVINCE_LIST_FAIL='PROVINCE_LIST_FAIL'


export const LANGUAGE_LIST_REQUEST='LANGUAGE_LIST_REQUEST'
export const LANGUAGE_LIST_SUCCESS='LANGUAGE_LIST_SUCCESS'
export const LANGUAGE_LIST_FAIL='LANGUAGE_LIST_FAIL'


