

export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";


export const CONFIRM_PIN_REQUEST = "CONFIRM_PIN_REQUEST";
export const CONFIRM_PIN_SUCCESS = "CONFIRM_PIN_SUCCESS";
export const CONFIRM_PIN_FAIL = "CONFIRM_PIN_FAIL";


export const RESET_RECHARGE_STATE = "RESET_RECHARGE_STATE";
export const PIN_CONFIRMED = "PIN_CONFIRMED";
export const ORDER_PLACED = "ORDER_PLACED"; 


export const CLEAR='CLEAR_STATE'

export const PLACE_CUSTOM_RECHARGE_REQUEST = "PLACE_CUSTOM_RECHARGE_REQUEST";
export const PLACE_CUSTOM_RECHARGE_SUCCESS = "PLACE_CUSTOM_RECHARGE_SUCCESS";
export const PLACE_CUSTOM_RECHARGE_FAIL = "PLACE_CUSTOM_RECHARGE_FAIL";
