export const SUB_RESELLER_LIST_REQUEST='SUB_RESELLER_LIST_REQUEST'
export const SUB_RESELLER_LIST_SUCCESS='SUB_RESELLER_LIST_SUCCESS'
export const SUB_RESELLER_LIST_FAIL='SUB_RESELLER_LIST_FAIL'


export const ADD_SUB_RESELLER_REQUEST='ADD_SUB_RESELLER_REQUEST'
export const ADD_SUB_RESELLER_SUCCESS='ADD_SUB_RESELLER_SUCCESS'
export const ADD_SUB_RESELLER_FAIL='ADD_SUB_RESELLER_FAIL'


export const SET_SUB_RESELLER_PASSWORD_REQUEST = 'SET_SUB_RESELLER_PASSWORD_REQUEST';
export const SET_SUB_RESELLER_PASSWORD_SUCCESS = 'SET_SUB_RESELLER_PASSWORD_SUCCESS';
export const SET_SUB_RESELLER_PASSWORD_FAIL = 'SET_SUB_RESELLER_PASSWORD_FAIL';


export const CHANGE_BALANCE_REQUEST = 'CHANGE_BALANCE_REQUEST';
export const CHANGE_BALANCE_SUCCESS = 'CHANGE_BALANCE_SUCCESS';
export const CHANGE_BALANCE_FAIL = 'CHANGE_BALANCE_FAIL';


export const CHANGE_SUB_RESELLER_STATUS_REQUEST = 'CHANGE_SUB_RESELLER_STATUS_REQUEST';
export const CHANGE_SUB_RESELLER_STATUS_SUCCESS = 'CHANGE_SUB_RESELLER_STATUS_SUCCESS';
export const CHANGE_SUB_RESELLER_STATUS_FAIL = 'CHANGE_SUB_RESELLER_STATUS_FAIL';


export const DELETE_SUB_RESELLER_REQUEST = 'DELETE_SUB_RESELLER_REQUEST';
export const DELETE_SUB_RESELLER_SUCCESS = 'DELETE_SUB_RESELLER_SUCCESS';
export const DELETE_SUB_RESELLER_FAIL = 'DELETE_SUB_RESELLER_FAIL';


export const SINGLE_SUB_RESELLER_REQUEST='SINGLE_SUB_RESELLER_REQUEST'
export const SINGLE_SUB_RESELLER_SUCCESS='SINGLE_SUB_RESELLER_SUCCESS'
export const SINGLE_SUB_RESELLER_FAIL='SINGLE_SUB_RESELLER_FAIL'

export const CLEAR='CLEAR_STATE'
